# Generated by Django 3.2.13 on 2022-09-30 03:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dahwe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='대회명')),
                ('start_Date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_Date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='subject_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SorP', models.BooleanField()),
                ('User_ID', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('User_password', models.CharField(max_length=20)),
                ('User_name', models.CharField(max_length=16, verbose_name='이름')),
                ('User_email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('Nick_Name', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('Hakgwa', models.CharField(max_length=20, unique=True, verbose_name='학과')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Hakbun', models.IntegerField(default=0)),
                ('Win', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.dahwe')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
                ('category', models.IntegerField(default=0)),
                ('company', models.IntegerField(default=0)),
                ('subject_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.subject_table')),
            ],
        ),
    ]
