# Generated by Django 3.2.13 on 2022-09-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20220930_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
