# Generated by Django 3.2.13 on 2022-09-30 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_user_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='아이디')),
                ('sender', models.CharField(max_length=16, verbose_name='이름')),
                ('recieve_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
