# Generated by Django 3.2.13 on 2022-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_auto_20220930_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='everyinfo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('professor', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=70)),
                ('distribution', models.CharField(max_length=30)),
            ],
        ),
    ]
