import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django
django.setup()
import pandas as pd
from models import subject_table

subjects = pd.read_csv('subject.csv')

for a,i in subjects.iterrows():
    subject = subject_table.objects.create()
    subject.물리학및실험1 = i[2]
    subject.미분적분학 = i[3]
    subject.선형대수 = i[4]
    subject.확률및랜덤변수 = i[5]
    subject.미분방정식 = i[6]
    subject.이산구조 = i[7]
    subject.디자인적사고 = i[8]
    subject.웹파이선프로그래밍 = i[9]
    subject.객체지향프로그래밍 = i[10]
    subject.논리회로 = i[11]
    subject.컴퓨터구조 = i[12]
    subject.자료구조 = i[13]
    subject.운영체제 = i[14]
    subject.컴퓨터네트워크 = i[15]
    subject.소프트웨어공학 = i[16]
    subject.알고리즘분석 = i[17]
    subject.데이터베이스 = i[18]
    subject.오픈소스SW개발 = i[19]
    subject.IT기술영어1 = i[20]
    subject.IT기술영어2 = i[21]
    subject.IT기술영어3 = i[22]
    subject.캡스톤디자인1 = i[23]
    subject.캡스톤디자인2 = i[24]
    subject.졸업논문 = i[25]
    subject.기계학습 = i[26]
    subject.신호와시스템 = i[27]
    subject.문제해결 = i[28]
    subject.형식언어및컴파일러 = i[29]
    subject.파일처리 = i[30]
    subject.멀티미디어시스템 = i[31]
    subject.시스템분석및설계 = i[32]
    subject.프로그래밍언어구조론 = i[33]
    subject.SW스타트업비즈니스 = i[34]
    subject.SW스타트업프로젝트 = i[35]
    subject.최신기술프로젝트1 = i[36]
    subject.최신기술프로젝트2 = i[37]
    subject.최신기술콜로키움1 = i[38]
    subject.최신기술콜로키움2 = i[39]
    subject.단기현장실습 = i[40]
    subject.장기현장실습 = i[41]
    subject.연구연수활동1 = i[42]
    subject.연구연수활동2 = i[43]
    subject.독립심화학습1 = i[44]
    subject.독립심화학습2 = i[45]
    subject.인공지능 = i[46]
    subject.빅데이터프로그래밍 = i[47]
    subject.클라우드컴퓨팅 = i[48]
    subject.데이터센터프로그래밍 = i[49]
    subject.정보보호 = i[50]
    subject.모바일프로그래밍 = i[51]
    subject.웹서비스프로그래밍 = i[52]
    subject.리눅스시스템프로그래밍 = i[53]
    subject.IoT디지털시스템 = i[54]
    subject.IoT소프트웨어 = i[55]
    subject.로봇스프트웨어 = i[56]
    subject.영상처리 = i[57]
    subject.컴퓨터그래픽스 = i[58]
    subject.멀티미디어처리 = i[59]
    subject.인간컴퓨터상호작용 = i[60]
    subject.UI_UX프로그래밍 = i[61]
    subject.컴퓨터비전 = i[62]
    subject.AI네트워킹 = i[63]
    subject.IoT네트워크 = i[64]
    subject.딥러닝 = i[65]
    subject.실전기계학습 = i[66]
    subject.save()
